### ISSUE TITLE
Missing fields (zimbra)

### ISSUE THREAD

**Issue by miquelangeld** [darold/sendmailanalyzer#34]
I'm wondering if it's possible to get the blank fields like  "recipients" and also know where com from the Id FaKeJb3dcXK8GQZtzOUz
http://screenpresso.com/=ngYHe

Thanks in advance.

**Comment by darold** [comment]
Hi,

The id starting with FaKe is explicitly a fake id created by sendmailanalyzer because there is no ID field in the log file for this information. If there is no value in the recipient field, this is because this information is not available, with no ID it is impossible for SA to associate sender/recipient. But here you seems to have the recipient address in the status field.

Regards,
