### ISSUE TITLE
month with 31 days

### ISSUE THREAD

**Issue by psvillanueva2015** [darold/sendmailanalyzer#64]
Hi,

Just an observation I've installed version 9.2 but Month with 31 calendar days is not showing up the whole 31 days, example January 2019 has 31 days but only 27 days are visible and 28,29,30 and 31 are missing. Is there a fix on this?

Thanks,
Pete

**Comment by darold** [comment]
Hi,

Are you sure that the system has enough disk space or something else that force sendmailanalyzer to stop working? SendmailAnalyzer just look at available year/month/day repository on the system to display a link to the daily statistics. Maybe something goes wrong and repository are not generated.

If you use default installation have a look to /usr/local/sendmailanalyzer/2018/12/ directory if you have 28,29,30 and 31 sub directory. If they doesn't exists your sendmailanalyzer has been stopped since 27th December.

**Comment by psvillanueva2015** [comment]
Hi Gilles,

Thanks for your reply, I'm referring to the screenshot below. box in red

[image: image.png]

Regards,
Pete

**Comment by darold** [comment]
I can't see the screenshot on github send it to my private email gilles AT darold DOT net.

**Comment by darold** [comment]
Commit e047022 solves the issue. Please update to latest development code.
