### ISSUE TITLE
Blank Reporting?

### ISSUE THREAD

**Issue by jeff3d29** [darold/sendmailanalyzer#81]
New to sendmail and sendmailreporting.

I have deploy my first Sendmail MTA now, I want to see the reporting so deploy sendmailanalyzer on separate server as didn't felt right having on the same server as the MTA. I believe I configure everything correctly but being receving no report or chart. What did I miss?

![image](https://user-images.githubusercontent.com/101384775/157817535-a1c15824-294d-48e6-a95f-6a8860047d05.png)

**Comment by darold** [comment]
Hi,

I'm surprised by the blank artound the mail0 server name. Can you please post few line of your log or send then to my private email also give me the command line you are using to execute sendmailanalyzer.

Also are you using rsyslog to send your log to the other server or are you copying the log?

**Comment by jeff3d29** [comment]
@darold I'm using rsyslog to send the logs from the MTA to sendmailanalyzer. I send a private message, using /usr/local/sendmailanalyzer -f

**Comment by pmvo51** [comment]
Friends, I also did my first install of Sendmailanalyzer and the graphs were not generated.

Another error found was when manually executing sa_report.cgi because I had an error "Language file is not readable lang/en_US". I needed to comment out this function to get it to run successfully.

Can you help me?

![image](https://user-images.githubusercontent.com/94560880/169552942-65a2dc49-fedf-4451-8490-2c6ad881bda3.png)

**Comment by darold** [comment]
you need to copy the lang/ directory from the sources where the sa_report.cgi is installed. You CGI directory where sa_report.cgi is install should looks to the default:
```
$ tree /usr/local/sendmailanalyzer/www/
/usr/local/sendmailanalyzer/www/
├── flotr2.js
├── lang
│   ├── bg_BG
│   ├── de_DE
│   ├── en_US
│   ├── ERROR_CODE
│   ├── es_ES
│   ├── fr_FR
│   ├── it_IT
│   ├── pt_BR
│   └── ru_RU
├── salogo.png
├── sa_report.cgi
└── sorttable.js
```
If this is the case, you should verify the permission, files here probably need to be readable by the www-data user or the one your httpd server is running.

**Comment by darold** [comment]
@jeff3d29 I don't remember if this issue has been solved and can be closed, can you confirm please?

**Comment by pmvo51** [comment]
@darold 

Thank you!
Now I can evolve because I really had to give permission on the "lang" folder.

==> The next step is to have the graphics generation. I'm sending the logs via rsyslog (see tree below).

/var/log/remote/
├── auth
│   └── ServerName
│       ├── xxxxx.log
│       ├── xxxxx.log
│       ├── xxxxx.log
│       
└── msg
    ├── ServerName
    │   ├── xxxxx.log
    │   ├── xxxxx.log
    │   ├── xxxxx.log

![image](https://user-images.githubusercontent.com/94560880/169580008-ec297792-27d5-4810-a1ff-637fdf89f90e.png)

**Comment by pmvo51** [comment]
**Hello, anybody help me, please?**

![image](https://user-images.githubusercontent.com/94560880/169851545-b7c9a83e-8aea-4521-9ed2-902b5e55b2b4.png)

**Comment by darold** [comment]
Hi, I can not help much more on this outside saying that it should works. If you can send to my private email < gilles AT darold DOT net > a tarball of your logs I will try to reproduce your issue.

**Comment by pmvo51** [comment]
@darold 
Solved!

My friend, just to register that the graphics were not being generated because I needed to change the selinux context of the directory where the caches are stored (here: /var/lib/sendmailanalyzer/) and I used the context: httpd_sys_content_t.
After this change the graphics opened normally.

Thanks!

**Comment by jeff3d29** [comment]
All,

Apologies for not getting back sooner on this matter. The matter was fixed by updating policies in the reporting server to allow incoming data via rsyslog. Once that was set, it was a matter of updating apache to be able to read it.
